<a href="https://colab.research.google.com/github/MANS555/AIML_TRAINING_MANISH_SAHU/blob/main/assignment%201%20avg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 1

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [17]:
import matplotlib.image as img


In [15]:
import torch
from torch.nn import Conv2d

In [21]:
import cv2
import numpy as np


# Read the image
img = cv2.imread('avg.jpg', 0)

# Obtain number of rows and columns
# of the image
m, n = img.shape

# Develop Averaging filter(3, 3) mask
mask = np.ones([3, 3], dtype = int)
mask = mask / 9

# Convolve the 3X3 mask over the image
img_new = np.zeros([m, n])

for i in range(1, m-1):
    for j in range(1, n-1):
        temp = img[i-1, j-1]*mask[0, 0]+img[i-1, j]*mask[0, 1]+img[i-1, j + 1]*mask[0, 2]+img[i, j-1]*mask[1, 0]+ img[i, j]*mask[1, 1]+img[i, j + 1]*mask[1, 2]+img[i + 1, j-1]*mask[2, 0]+img[i + 1, j]*mask[2, 1]+img[i + 1, j + 1]*mask[2, 2]

        img_new[i, j]= temp

img_new = img_new.astype(np.uint8)
cv2.imwrite('blurred.tif', img_new)
print(img_new)
plt.show()

[[  0   0   0 ...   0   0   0]
 [  0  87 127 ...  13   9   0]
 [  0 129 187 ...  19  14   0]
 ...
 [  0  12  18 ... 143  95   0]
 [  0   8  12 ...  93  62   0]
 [  0   0   0 ...   0   0   0]]
